# Generated by Django 5.1.3 on 2026-04-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_customer_lat_order_customer_lng'),
    ]

    operations = [
    ]
