# Generated by Django 5.1.3 on 2026-04-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_preorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='preorder_date',
            field=models.DateField(blank=True, help_text='Customer requested preorder delivery/pickup date', null=True),
        ),
    ]
