# Generated by Django 5.1.3 on 2026-04-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
